env: "local"
storage_path: ""
token_ttl: 20m
grpc:
  host: "localhost"
  port: 8080
  retries_count: 5
  timeout: 3s
  insecure: true
postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  db_name: "postgres"
  ssl_mode: "disable"